language: cpp

# CUDA stuff inspired by https://github.com/jeremad/cuda-travis/blob/master/.travis.yml

jobs:
  include:
    - os: linux
      env:
        - CUDA=cuda-10-2_10.2.89-1
        - CUDA_SHORT=10.2
        - UBUNTU_VERSION=ubuntu1804
      dist: bionic
      compiler: gcc
      before_install:
        - pip install --user cpp-coveralls
        - INSTALLER=cuda-repo-${UBUNTU_VERSION}_${CUDA}_amd64.deb
        - wget http://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/${INSTALLER}
        - sudo dpkg -i ${INSTALLER}
        - wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/7fa2af80.pub
        - sudo apt-key add 7fa2af80.pub
        - sudo apt update -qq
        - sudo apt install -y cuda-core-${CUDA_SHORT/./-} cuda-cudart-dev-${CUDA_SHORT/./-} cuda-cufft-dev-${CUDA_SHORT/./-}
        - sudo apt clean
        - CUDA_HOME=/usr/local/cuda-${CUDA_SHORT}
        - LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
        - PATH=${CUDA_HOME}/bin:${PATH}
        - wget https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip
        - unzip ninja-linux.zip
        - PATH=${PATH}:${PWD}
      script:
        - mkdir cmake-build-debug
        - cd cmake-build-debug
        - cmake -DCOVERAGE=1 ../
        - cmake --build . -- -j2
        - ./runUnitTests
      after_success:
        - coveralls -r ../ -i "src/" --exclude "lib" --exclude "tests" --gcov-options '\-lp' --verbose
    - os: osx
      compiler: clang
      script:
        - mkdir cmake-build-debug
        - cd cmake-build-debug
        - cmake -DCOVERAGE=0 ../
        - cmake --build . -- -j2
          
          http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-10-2_10.2.89-1_amd64.deb