language: cpp

before_install:
  - pip install --user cpp-coveralls

script:
  - cmake -DCOVERAGE=1 .
  - cmake --build .
  - ./runUnitTests

after_success:
  - coveralls --root . -E ".*googletest.*" -E ".*CMakeFiles.*" -E ".*polytope/lib/.*" -E ".*polytope/tests/.*" -E "/usr/.*"