language: cpp

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - cmake -DCOVERAGE=1 ../
  - cmake --build .
  - ./runUnitTests

after_success:
  - coveralls -r ../ -i "src/" --exclude "lib" --exclude "tests" --gcov-options '\-lp' --verbose