language: cpp

before_install:
  - pip install --user cpp-coveralls

script:
  - cmake -DCOVERAGE=1 .
  - cmake --build .
  - ls -l
  - ./runUnitTests
  - ls -l

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
  - ls -l